// Main
export const SET_ALL_PRODUCTS = 'SET_ALL_PRODUCTS';
// Cart
export const CART_STATE = 'CART_STATE';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
export const ADD_IDS = 'ADD_IDS';
export const DELETE_IDS = 'DELETE_IDS';
export const CART_ADD_SUBTOTAL = 'CART_ADD_SUBTOTAL';
export const CART_SUBTRACT_SUBTOTAL = 'CART_SUBTRACT_SUBTOTAL';
export const RESET_CART = 'RESET_CART';
// Admin page
export const ADDED_NEW_PRODUCT = 'ADDED_NEW_PRODUCT';